controller_list:
  - name: /vuasrl_manipulation_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: /vuasrl_manipulation_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - grip_joint
      - grip_joint_sub