  vuasrl_manipulation_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.0
        joint1: {trajectory: 0.1, goal: 0.1}
        joint2: {trajectory: 0.1, goal: 0.1}
        joint3: {trajectory: 0.1, goal: 0.1}
        joint4: {trajectory: 0.1, goal: 0.1}
        stop_trajectory_duration: 0.5
        state_publish_rate:  25
        action_monitor_rate: 10
    
  vuasrl_manipulation_gripper_controller:
    type: effort_controllers/JointTrajectoryController
    gains: 
      grip_joint: {p: 300.0, i: 0.1 ,d: 1.0 ,i_clamp: 0.2}
      grip_joint_sub: {p: 300.0, i: 0.1 ,d: 1.0 ,i_clamp: 0.2}
    joints:
      - grip_joint
      - grip_joint_sub
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.0
        grip_joint: {trajectory: 0.1, goal: 0.1}
        grip_joint_sub: {trajectory: 0.1, goal: 0.1}
        stop_trajectory_duration: 0.5
        state_publish_rate:  25
        action_monitor_rate: 10
