controller_list:
  - name: /smart_tugcar/smart_tugcar_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: /smart_tugcar/smart_tugcar_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - gripper

